version: '3.8'

networks:
  elastic-net:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14
    container_name: enterprise-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enterprise_content_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elastic-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: enterprise-content-platform-elasticsearch-1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: enterprise-content-platform-kibana-1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

  app:
    build: .
    container_name: enterprise-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - elastic-net
